web:
  restart: always
  build: .
  command: npm start
  ports:
    - "80:80"
  links:
    - db
  volumes:
    - ./data/files:/usr/src/app/public/files
  environment:
    - VIRTUAL_HOST=lordofthecode.nl,www.lordofthecode.nl
    - MONGO_URI=mongodb://db/lotc
    - PORT=80
    - DOMAIN=www.lordofthecode.nl
db:
  restart: always
  image: mongo:3.0.2
  volumes:
    - ./data/db:/data/db
